@startuml
| Model |
:Client;
#LightBlue :Injects;
|View Model|
if () then ( )
#pink :Data Model;
else ( )
#Pink :Swimlane Theme;
endif 
#LightBlue :Info;
#pink :Swimline Presenter;
#LightBlue :Manages;
|Swimlane View|
#pink :Swimlane View;
|View|
#LightBlue :Invokes;
#pink :Native Drawing APIs;
kill
@enduml
