@startuml
| Swimlane1 |
#Pink:App Layer;
#LightBlue :Injects;
| Swimlane2 |
switch () 
case ( )
    #Pink : Swimlane Theme;
case ( )
    #Pink : Data Models;
case ( )
    #Pink : Swimlane Config;
endswitch
| Swimlane2 |
#LightBlue :Into;
#Pink :Swimlane Presenter;
#LightBlue :Manages;
| Swimlane3 |
#Pink:Swimlane View;
| Swimlane4 |
#LightBlue :Invokes;
#Pink :Naitivie Drawing APIs;
@enduml
